services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./.env
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - '3000:8080'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env

volumes:
  db_data: